### PR TITLE
Firestore: Remove firestore_cc_library

### PR DESCRIPTION
**Pull request by alexames**
All exception-enabled builds should be done with --define=firestore_exceptions=1

PiperOrigin-RevId: 356770616

### CODE REVIEW

**Review by jonsimantov — COMMENTED** [review]
I'm pretty sure that this file should just be completely removed from the repo.

**Comment by alexames** [comment]
> I'm pretty sure that this file should just be completely removed from the repo.

Done.

**Review by var-const — APPROVED** [review]
I'm not sure how it looks from history perspective (this is a change that didn't exist in google3), but otherwise LGTM.

**Comment by alexames** [comment]
Originally this PR was an export of a google3 change, but it was a change to a script that did blaze builds, which we don't need anymore, so at Jon's suggestion I just removed it.

**Pull request merged**
