### PR TITLE
fix storage integration testapp for iOS 

### PR DESCRIPTION
**Pull request by sunmou99**
I believe this commit causing the iOS test fail: https://github.com/firebase/firebase-cpp-sdk/commit/3ece8b2f28ade78f6b8991833d01544ac31d4866# @DellaBitta 

And I was wondering if should we sync the changes into google3.

### CODE REVIEW

**Comment by DellaBitta** [comment]
What aspect of the test is broken by the prior change?  Also there were multiple locations where I replaced a simple timed wait with a tight loop waiting for data to be sent.  Does this change need to be made at all of those other locations, too?

**Comment by sunmou99** [comment]
> What aspect of the test is broken by the prior change? 

It breaks FirebaseStorageTest.TestLargeFilePauseResumeAndDownloadCancel in [iOS](https://github.com/firebase/firebase-cpp-sdk/runs/1278097351?check_suite_focus=true). 

> Also there were multiple locations where I replaced a simple timed wait with a tight loop waiting for data to be sent. Does this change need to be made at all of those other locations, too?
I don't think so. Some locations doesn't affect Mobile Platform, and others doesn't break the mobile tests. I believe this is the only place need to change. iOS tests [passed](https://github.com/firebase/firebase-cpp-sdk/runs/1278389281?check_suite_focus=true) after the change.

**Comment by anonymous-akorn** [comment]
Additional context in b/171415295

Is it possible this is also causing the issues for Android?

**Comment by sunmou99** [comment]
> Is it possible this is also causing the issues for Android?

I don't think so. https://github.com/firebase/firebase-cpp-sdk/commit/3ece8b2f28ade78f6b8991833d01544ac31d4866 has nothing to do with 'FirebaseStorageTest.TestDeleteFile'. Also, the Android (Mac) tests [passed](https://github.com/firebase/firebase-cpp-sdk/runs/1278097336?check_suite_focus=true) on dev branch.

**Comment by DellaBitta** [comment]
I verified the test on Android as well. Great!

**Review by DellaBitta — APPROVED** [review]

**Review by anonymous-akorn — APPROVED** [review]

**Pull request merged**
