### PR TITLE
Setup Desktop test workflow that detects C++ SDK breakage caused by iOS SDK changes

### PR DESCRIPTION
**Pull request by sunmou99**
### Description
Add nightly workflow that run firebase desktop tests against iOS tip-of-tree branch.
Also, generate the result report and send to Firestore Nightly Report.

Note: desktop build failed on Windows. Uploaded log files to the original ticket.

Other: Fix "build desktop script does not throw errors". e.g. https://github.com/firebase/firebase-cpp-sdk/actions/runs/3632775054/jobs/6129012424#step:14:1681

[replace this line]: # (Describe your changes in detail.)
***
### Testing
https://github.com/firebase/firebase-cpp-sdk/actions/runs/3635116249
report: https://github.com/firebase/firebase-cpp-sdk/issues/835

[replace this line]: # (Describe your testing in detail.)
***

### Type of Change
Place an `x` the applicable box:
- [x] Bug fix. Add the issue # below if applicable.
- [ ] New feature. A non-breaking change which adds functionality.
- [x] Other, such as a build process or documentation change.
***

#### Notes
- Bug fixes and feature changes require an update to the `Release Notes` section of `release_build_files/readme.md`.
- Read the contribution guidelines [CONTRIBUTING.md](https://github.com/firebase/firebase-cpp-sdk/blob/main/CONTRIBUTING.md).
- Changes to the public API require an internal API review. If you'd like to help us make Firebase APIs better, please propose your change in a feature request so that we can discuss it together.

### CODE REVIEW

**Comment by dconeybe** [comment]
@sunmou99 Could you re-trigger the test run that surfaced the Windows build error? I've pushed up a commit to this branch that may fix it by setting git's core.eol config setting to lf: https://github.com/firebase/firebase-cpp-sdk/pull/1162/commits/e5a4993750433ec9bdddafc7cf6c012ecf6e2257

**Comment by dconeybe** [comment]
> @sunmou99 Could you re-trigger the test run that surfaced the Windows build error? I've pushed up a commit to this branch that may fix it by setting git's core.eol config setting to lf: [e5a4993](https://github.com/firebase/firebase-cpp-sdk/commit/e5a4993750433ec9bdddafc7cf6c012ecf6e2257)

@sunmou99 did this core.eol change help anything?

**Comment by sunmou99** [comment]
> > @sunmou99 Could you re-trigger the test run that surfaced the Windows build error? I've pushed up a commit to this branch that may fix it by setting git's core.eol config setting to lf: [e5a4993](https://github.com/firebase/firebase-cpp-sdk/commit/e5a4993750433ec9bdddafc7cf6c012ecf6e2257)
> 
> @sunmou99 did this core.eol change help anything?

Yes, but the build job still failed.

**Comment by dconeybe** [comment]
Hmm. @sunmou99 @ehsannas what do you think about merging this PR with Windows disabled, and then we can work on fixing the windows build in a separate PR? It would be good to have _some_coverage. The marginal gain from adding Windows to the test matrix is quite small.

**Comment by ehsannas** [comment]
@dconeybe @sunmou99 yeah I think it's still valuable to enable these bots for Linux and macOS.

@dconeybe should we land your commit with the new `git config` too? or do you want to revert that?

**Comment by dconeybe** [comment]
> @dconeybe @sunmou99 yeah I think it's still valuable to enable these bots for Linux and macOS.
> 
> @dconeybe should we land your commit with the new `git config` too? or do you want to revert that?

My commit should be reverted, since it didn't fix anything.

**Comment by sunmou99** [comment]
> > @dconeybe @sunmou99 yeah I think it's still valuable to enable these bots for Linux and macOS.
> > @dconeybe should we land your commit with the new `git config` too? or do you want to revert that?
> 
> My commit should be reverted, since it didn't fix anything.

reverted

**Review by ehsannas — APPROVED** [review]

**Pull request merged**
