### PR TITLE
GitHub REST API: add timeout and retry 

### PR DESCRIPTION
**Pull request by sunmou99**
Existing http request flakiness in step "Update PR label and comment": https://github.com/firebase/firebase-cpp-sdk/runs/2945372323?check_suite_focus=true#step:18:23
Should be fixed now.

Add timeout (5s) to all GitHub REST API requests.
Add retry (3 times) to all query and update requests.

### CODE REVIEW

**Comment by sunmou99** [comment]
add comment test

**Comment by sunmou99** [comment]
add comment test

**Review by vimanyu — COMMENTED** [review]
One clarification, do we not want to use retries on "put" and "patch" requests?

**Comment by sunmou99** [comment]
> One clarification, do we not want to use retries on "put" and "patch" requests?

We retries on "patch".
I don't retry on "post", because retry may add duplicate comments.

**Review by vimanyu — APPROVED** [review]
LGTM!

**Pull request merged**
