### PR TITLE
Update build & test summary report

### PR DESCRIPTION
**Pull request by sunmou99**
- Expand matrix in `print_matrix_configuration.py` (not in real workflow)
- To set a test device, now could either uses flags `--android_model Pixel2 --android_version 28` or `--android_device android_target` in `test_lab.py`.
   - Similar for `test_simulator.py`
- Now log results also contain "failed tests", "test failure info" and "[ftl link](https://firebase.corp.google.com/u/0/project/games-auto-release-testing/testlab/histories/bh.3d4f9f100256786f/matrices/7446883717188469483) (for ftl test)".
- Now generate a new json format log result `*.log.json`
- Update `summarize_test_results.py`, now the summary focus on Testapps.  The summary also combines Configs, and shows Failed Tests.
   - To get access to the test failure info & FTL link, please download the log artifacts.
   - Test failure info in the comment? Add this feature added first, but removed. Because even with a drop-down list, the failure info is not quite readable in a small table. 
   - FTL link in the comment? Not implement, must disable "combine test device" feature first.
- Some code cleaning

- TODO: What are the [flaky tests](https://docs.google.com/spreadsheets/d/1syx16yckkc1vEBkf4q9z29zMcdex6xvz6i6KGHucrfE/edit?resourcekey=0-MiQA7zBr-OGv2_litgYPRQ#gid=0)?

### CODE REVIEW

**Comment by sunmou99** [comment]
<details>
<summary>Well</summary>

<details>
<summary>Try this</summary>

 <details>
 <summary>The other one</summary>

   <details>
   <summary>Ok, try this</summary>
   You got me 😂
   </details>
 </details>
</details>
</details>

**Comment by sunmou99** [comment]
| Failures | Configs |
|----------|---------|
| admob | [Build] [Windows] [boringssl] |
| analytics | [Build] [Windows] [boringssl] |
| auth | [Build] [Windows] [boringssl]<br/>[Test] [iOS] [macos] [All Simulators] |
| database | [Build] [Windows] [boringssl]<br/>[Test] [iOS] [macos] [All Simulators] |
| dynamic_links | [Build] [Windows] [boringssl]<br/>[Test] [Android] [All os] [emulator_latest]<br/>[Test] [Android] [All os] [emulator_min] |
| firestore | <details><summary>_(9 items)_</summary>[Build] [Windows] [boringssl]<br/>[Test] [Android] [All os] [emulator_min]<br/>[Test] [Android] [macos] [android_target]<br/>[Test] [Android] [ubuntu] [android_min]<br/>[Test] [Android] [ubuntu] [emulator_target]<br/>[Test] [Android] [windows, macos] [android_min]<br/>[Test] [Android] [windows] [emulator_target]<br/>[Test] [iOS] [macos] [simulator_latest, simulator_min]<br/>[Test] [iOS] [macos] [simulator_target]</details> |
| functions | [Build] [Windows] [boringssl]<br/>[Test] [iOS] [macos] [All Simulators] |
| installations | [Build] [Windows] [boringssl]<br/>[Test] [iOS] [macos] [simulator_latest]<br/>[Test] [iOS] [macos] [simulator_min]<br/>[Test] [iOS] [macos] [simulator_target] |
| messaging | <details><summary>_(11 items)_</summary>[Build] [Windows] [boringssl]<br/>[Test] [Android] [macos] [android_min]<br/>[Test] [Android] [macos] [android_target]<br/>[Test] [Android] [macos] [emulator_latest, emulator_min]<br/>[Test] [Android] [macos] [emulator_target]<br/>[Test] [Android] [ubuntu] [android_min]<br/>[Test] [Android] [ubuntu] [android_target]<br/>[Test] [Android] [ubuntu] [emulator_min, emulator_latest]<br/>[Test] [Android] [windows] [android_min]<br/>[Test] [Android] [windows] [android_target]<br/>[Test] [Android] [windows] [emulator_latest, emulator_min]</details> |
| remote_config | [Build] [Windows] [boringssl]<br/>[Test] [iOS] [macos] [simulator_latest]<br/>[Test] [iOS] [macos] [simulator_min]<br/>[Test] [iOS] [macos] [simulator_target] |
| storage | [Build] [Windows] [boringssl]<br/>[Test] [iOS] [macos] [simulator_latest]<br/>[Test] [iOS] [macos] [simulator_min]<br/>[Test] [iOS] [macos] [simulator_target] |

**Review by DellaBitta — APPROVED** [review]

**Review by jonsimantov — DISMISSED** [review]

**Review by jonsimantov — APPROVED** [review]
Pre-emptive approval assuming the tests pass. :)

**Comment by sunmou99** [comment]
Each run I got a flaky test failed😭:
1st run: [FirebaseInstallationsTest.TestGettingTokenTwiceMatches on ubuntu](https://github.com/firebase/firebase-cpp-sdk/runs/2768140541?check_suite_focus=true#step:16:50)
2ed run: [FirebaseInstallationsTest.TestGettingTokenTwiceMatches on mac](https://github.com/firebase/firebase-cpp-sdk/runs/2769066131?check_suite_focus=true#step:16:50)
3rd run [FirebaseAuthTest.TestPhoneAuth](https://github.com/firebase/firebase-cpp-sdk/runs/2769969295?check_suite_focus=true#step:16:52)

I added these two flaky test in this [sheet](https://docs.google.com/spreadsheets/d/1syx16yckkc1vEBkf4q9z29zMcdex6xvz6i6KGHucrfE/edit?resourcekey=0-MiQA7zBr-OGv2_litgYPRQ#gid=0).

**Pull request merged**
