### PR TITLE
Update googletest dependency to a pinned commit from April 2022.

### PR DESCRIPTION
**Pull request by jonsimantov**
[replace this line]: # (Describe your changes in detail.)
***

[replace this line]: # (Describe your testing in detail.)
***

### Type of Change
Place an `x` the applicable box:
- [ ] Bug fix. Add the issue # below if applicable.
- [ ] New feature. A non-breaking change which adds functionality.
- [ ] Other, such as a build process or documentation change.
***

#### Notes
- Bug fixes and feature changes require an update to the `Release Notes` section of `release_build_files/readme.md`.
- Read the contribution guidelines [CONTRIBUTING.md](https://github.com/firebase/firebase-cpp-sdk/blob/main/CONTRIBUTING.md).
- Changes to the public API require an internal API review. If you'd like to help us make Firebase APIs better, please propose your change in a feature request so that we can discuss it together.

### CODE REVIEW

**Comment by jonsimantov** [comment]
Still not sure if this will actually be required - so far our current googletest dependency (1.11.0) seems to be building okay in Xcode 13.3.1.

**Comment by dconeybe** [comment]
I think that the googletest issue with xcode 13.3.1 that surfaced in the iOS SDK (https://github.com/firebase/firebase-ios-sdk/pull/9705) came from an instantiated template. So perhaps this same build error isn't surfacing here, in the cpp sdk, because its test happen to not instantiate that template. Just a guess.

**Comment by jonsimantov** [comment]
This appears to not be required; closing for now.

**Comment by jonsimantov** [comment]
> I think that the googletest issue with xcode 13.3.1 that surfaced in the iOS SDK ([firebase/firebase-ios-sdk#9705](https://github.com/firebase/firebase-ios-sdk/pull/9705)) came from an instantiated template. So perhaps this same build error isn't surfacing here, in the cpp sdk, because its test happen to not instantiate that template. Just a guess.

Yep, that makes sense. Since we don't need it for our usage in C++, I'm closing this PR for now - we can always revisit it later. (I'd rather wait until a new official googletest release version occurs that includes the fix.)

**Comment by dconeybe** [comment]
@jonsimantov I don't think googletest will be doing releases anymore. According to https://github.com/google/googletest,

> GoogleTest now follows the "Abseil Live at Head philosophy". We recommend updating to the latest commit in the main branch as often as possible.

The last release, 11.1.0, was almost a year ago (June 2021). I wouldn't hold my breath for another official release version.

**Comment by jonsimantov** [comment]
> @jonsimantov I don't think googletest will be doing releases anymore. According to https://github.com/google/googletest,
> 
> > GoogleTest now follows the "Abseil Live at Head philosophy". We recommend updating to the latest commit in the main branch as often as possible.
> 
> The last release, 11.1.0, was almost a year ago (June 2021). I wouldn't hold my breath for another official release version.

Ah, good to know. Maybe it's worth resurrecting this PR then.

**Comment by dconeybe** [comment]
I think you need to update `testing/test_framework/download_googletest.py` as well:

https://github.com/firebase/firebase-cpp-sdk/blob/25da83cc70f38b71c3ffe8f964b579e6346756c3/testing/test_framework/download_googletest.py#L38-L41

**Comment by jonsimantov** [comment]
> The last release, 11.1.0, was almost a year ago (June 2021). I wouldn't hold my breath for another official release version.

It does look like official numbered releases are generally a year or two apart, so they may end up doing one at some point.

**Comment by dconeybe** [comment]
Well if there is no compelling reason to upgrade googletest, then I'm fine leaving it pinned at this year-old release. If it ain't broke, don't fix it.

**Pull request closed without merging**
