### PR TITLE
Feature/tvos support integration tests functions

### PR DESCRIPTION
**Pull request by vimanyu**
Changes done to XCode project for functions that allows us to run integration tests on device and simulator.

added a tvos target to XCode project for storage.
updated Podfile to build pods for tvos platform for this newly added target
To test this,

Make sure to have a valid GoogleService-Info.plist.
pod install
open integration_test.xcworkspace
Drag and drop firebase.xcframework, firebase_auth.xcframework and firebase_functions.xcframework

All tests pass on simulator and device.

### CODE REVIEW

**Review by DellaBitta — COMMENTED** [review]
You should remove files from xcuserdata/vimanyujain*, I think.

For instance, functions/integration_test/integration_test.xcodeproj/project.xcworkspace/xcuserdata/vimanyujain.xcuserdatad/UserInterfaceState.xcuserstate

**Review by DellaBitta — CHANGES_REQUESTED** [review]
Remove user-specific files

**Comment by sunmou99** [comment]
> I think you should remove files from xcuserdata/vimanyujain*, right?
> 
> * functions/integration_test/integration_test.xcodeproj/project.xcworkspace/xcuserdata/vimanyujain.xcuserdatad/UserInterfaceState.xcuserstate
> * functions/integration_test/integration_test.xcodeproj/xcuserdata/vimanyujain.xcuserdatad/xcschemes/xcschememanagement.plist
> * functions/integration_test/integration_test.xcworkspace/xcuserdata/vimanyujain.xcuserdatad/UserInterfaceState.xcuserstate

I remember that "integration_test.xcodeproj/project.pbxproj" is the only file we want under "integration_test.xcodeproj", we can safely remove the rest.  
This may apply to "integration_test.xcworkspace" as well.
@jonsimantov Could you provide more information?

**Comment by vimanyu** [comment]
Removed user specific files.

**Review by DellaBitta — APPROVED** [review]

**Pull request merged**
