### PR TITLE
Use build OS variables instead of hard coded build OS names

### PR DESCRIPTION
**Pull request by sunmou99**
### Description
Use build OS variables instead of hard coded build OS names
***
### Testing
Succeed:
https://github.com/firebase/firebase-cpp-sdk/actions/runs/2265168672
***

### Type of Change
Place an `x` the applicable box:
- [ ] Bug fix. Add the issue # below if applicable.
- [ ] New feature. A non-breaking change which adds functionality.
- [x] Other, such as a build process or documentation change.
***

#### Notes
- Bug fixes and feature changes require an update to the `Release Notes` section of `release_build_files/readme.md`.
- Read the contribution guidelines [CONTRIBUTING.md](https://github.com/firebase/firebase-cpp-sdk/blob/main/CONTRIBUTING.md).
- Changes to the public API require an internal API review. If you'd like to help us make Firebase APIs better, please propose your change in a feature request so that we can discuss it together.

### CODE REVIEW

**Comment by jonsimantov** [comment]
Can you merge from main (and resolve the conflicts) before I review?

**Review by jonsimantov — COMMENTED** [review]
So, the integration test summary says everything succeeded, BUT the Android emulator tests failed. Any idea why it was still reported as success? I think I've seen this happen before when the emulator test fails.

https://github.com/firebase/firebase-cpp-sdk/actions/runs/2272273221

**Comment by sunmou99** [comment]
> So, the integration test summary says everything succeeded, BUT the Android emulator tests failed. Any idea why it was still reported as success? I think I've seen this happen before when the emulator test fails.
> 
> https://github.com/firebase/firebase-cpp-sdk/actions/runs/2272273221

This is because we fail to locate the SDK artifacts, thus assuming it's a **build** error and ignore the **test** error.
This is a bug, and I fixed the artifacts path in the PR.

**Comment by jonsimantov** [comment]
Test failure seems unrelated, as far as I'm concerned this is good to merge.

**Pull request merged**
