### PR TITLE
Feature/rewarded user

### PR DESCRIPTION
**Pull request by berinhardt**

### CODE REVIEW

**Comment by berinhardt** [comment]
@googlebot I signed it!

**Comment by a-maurice** [comment]
Hi @berinhardt,

Thanks for sending the pull request!  Unfortunately we won't be able to accept it currently, as we are still working on setting up the test infrastructure for the repository, as we need to support a variety of build environments, and therefore don't have a great way to automatically verify it.  We'll be sure to reach out when we are in a position to bring this in.

Note that because this is a bigger change, which is adding new functions to the public headers (and thus changing the API surface), it might take a bit longer to verify.  When the repo is set up to take in pull requests, we will be sure to describe the workflow in the [CONTRIBUTING.md](https://github.com/firebase/firebase-cpp-sdk/blob/master/CONTRIBUTING.md).

Again, thanks for the interest, great to see people getting involved!

**Comment by jonsimantov** [comment]
Hi @berinhardt,

Sorry for the extremely long delay in getting a look at this PR. We finally have the infrastructure in place to take code submissions. If you're interested in getting this PR in, please merge the latest changes from main into it, and we can take a look.

Also note that there is now an AdMob integration test in admob/integration_test/src/integration_test.cc -- if you could add a test for this new functionality, that would be helpful.

Thanks!

**Comment by berinhardt** [comment]
Will do.

**Comment by berinhardt** [comment]
> Finally, one more note - to be able to use our testing infrastructure, this change should be made in a feature branch within this Git repo. You should have permissions to create a feature branch in the firebase/firebase-cpp-sdk project, and merge the changes from this PR into that branch.

Are you sure? I'm not being able to create that branch.

**Comment by DellaBitta** [comment]
> > Finally, one more note - to be able to use our testing infrastructure, this change should be made in a feature branch within this Git repo. You should have permissions to create a feature branch in the firebase/firebase-cpp-sdk project, and merge the changes from this PR into that branch.
> 
> Are you sure? I'm not being able to create that branch.

Interesting.  What's the command that you're running and what's the error? Thanks!

**Comment by berinhardt** [comment]
just tried to push a new branch named feature/RewardedUserId and returned error 403. What I'm not understanding?

**Comment by DellaBitta** [comment]
I don't know but we'll work it out!

How are you attempting to create a new branch?  I'm not familiar with a method in Github that would return HTTP request error codes, so learning more of the details about what you're attempting would be helpful.

I'm personally using the [git command line tools](https://git-scm.com/downloads), so my flow for creating a new branch would look something like this (assuming I've already git cloned the repo):

```
git checkout main
git pull
git branch feature/abc123
git checkout feature/abc123
```

_... make some changes to a file ..._

```
git add <file>
git commit -m "I changed a file"
git push --set-upstream origin feature/abc
```

Thanks.

**Comment by berinhardt** [comment]
Exactly like that, but when I try to push to the origin, it tries to push to https://github.com/firebase/firebase-cpp-sdk.git, and says 403

I'll try adding an ssh origin in order to see if I can get another error

**Comment by DellaBitta** [comment]
I was just able to reproduce this with a new account and using http as well.  I'm looking into it, but it would be great to know if ssh works.

**Comment by berinhardt** [comment]
with ssh doesn't work either

ERROR: Permission to firebase/firebase-cpp-sdk.git denied to berinhardt.

**Comment by DellaBitta** [comment]
Hi @berinhardt,

Thanks for bearing with us.  We're just getting used to how user submissions work so I'm sorry for the confusion. 

It turns out that the organization does not enable writes (pushes) by external contributors.  The process of creating a PR from a fork is the correct manner to contribute, as you've done.

I can also see that the tests are running.  If there's a problem that tests are failing due to the origin being a fork, then that's something that we'll have to work on.  A potential solution is for one of the admins to create a branch, merge your changes into it, and then we can re-execute the tests.  We'll see how this next text execution pans out.

**Comment by berinhardt** [comment]
all tests done

**Comment by berinhardt** [comment]
Something seems to be wrong with your integration tests

¡Error: Resource not accessible by integration?

**Comment by jonsimantov** [comment]
We've fixed our testing for contributors - if you merge main into your branch, I'll be able to trigger the full integration test suite on your PR manually.

**Comment by berinhardt** [comment]
Sorry for the delay

**Comment by berinhardt** [comment]
what else is needed for this?

**Comment by berinhardt** [comment]
@jonsimantov

**Pull request closed without merging**
