### PR TITLE
ReleaseDebugConfigSupport

### PR DESCRIPTION
**Pull request by crazyhappygame**
Support multiple configuration 
https://cmake.org/cmake/help/v3.16/variable/CMAKE_CONFIGURATION_TYPES.html#variable:CMAKE_CONFIGURATION_TYPES
https://cmake.org/cmake/help/v3.16/prop_tgt/MAP_IMPORTED_CONFIG_CONFIG.html

### CODE REVIEW

**Comment by crazyhappygame** [comment]
@googlebot I signed it!

**Comment by crazyhappygame** [comment]
@stewartmiles could you merge it?

**Comment by crazyhappygame** [comment]
@a-maurice could you merge it?

**Comment by a-maurice** [comment]
Hi @crazyhappygame, sorry for the delay in getting back to you.  Unfortunately, we have run into a couple roadblocks that have prevented us from setting up the repo to take in pull requests through GitHub (changes are being brought over from another repo, and it is currently one way, so this change would risk getting blown away).  The change does look reasonable though, so if you are fine with it, I can replicate your change into that repo, and push it onto this.

**Comment by crazyhappygame** [comment]
Ok

**Comment by crazyhappygame** [comment]
@a-maurice @DellaBitta I checked the latest version 8.3 and those changes are still not there...
Could you merge it?

**Pull request closed without merging**
