### PR TITLE
Add an initial version of App Check integration test

### PR DESCRIPTION
**Pull request by a-maurice**
Add an initial version of an integration test for App Check. It currently doesn't test much beyond creation of the providers.
***

Building and running the Android and Desktop versions locally
***

### Type of Change
Place an `x` the applicable box:
- [ ] Bug fix. Add the issue # below if applicable.
- [x] New feature. A non-breaking change which adds functionality.
- [ ] Other, such as a build process or documentation change.
***

#### Notes
- Bug fixes and feature changes require an update to the `Release Notes` section of `release_build_files/readme.md`.
- Read the contribution guidelines [CONTRIBUTING.md](https://github.com/firebase/firebase-cpp-sdk/blob/main/CONTRIBUTING.md).
- Changes to the public API require an internal API review. If you'd like to help us make Firebase APIs better, please propose your change in a feature request so that we can discuss it together.

### CODE REVIEW

**Comment by AlmostMatt** [comment]
To clarify, once this is committed will app check integration test be run as part of automated GHA integration test workflows? Will it run for all platforms?

If yes, can you link to a passing GHA workflow run, and if no, can you mention this in the PR description

**Comment by AlmostMatt** [comment]
This generally looks good, I just want to be sure that this won't break existing GHA workflows.

**Review by AlmostMatt — APPROVED** [review]
Looks good.
As discussed, runs of the integration test workflow specify which projects to test and the default is to not test app check. So this won't break existing integration test workflows.

Some of the tests currently failed because the stubs are not yet implemented (for example, create provider returns null), but this is ok since the existence of this test is helpful to assist in such implementation, and this test is not run automatically.

**Comment by a-maurice** [comment]
Note that the lint warning is because this adds encrypted files, which obviously aren't lint compatible.

**Pull request merged**
