### PR TITLE
Tie up the loose ends from moving Firestore's integration tests into integration_test_internal

### PR DESCRIPTION
**Pull request by dconeybe**
When Firestore's integration tests were moved to the `integration_test_internal` folder, there were a few loose ends that needed to be tied. This PR ties them up.

Changes in this PR include:
- Delete the files that were accidentally left behind in `firestore/src/tests/android`.
- Move the test `firebase_firestore_settings_android_test.cc` into `integration_test_internal`, which was accidentally missed.
- Re-apply some PRs whose test-related changes were missed in the move (i.e. #329, #330, #331).
- Re-enable the tests in `promise_android_test.cc` that were fixed by re-applying #331.

### CODE REVIEW

**Comment by dconeybe** [comment]
It looks like the integration tests are failing to build due to `firebase_firestore_settings_android_test.cc`, which was added in this PR. I'll push up a fix.

```
  /home/runner/work/firebase-cpp-sdk/firebase-cpp-sdk/ta/firestore/iti/src/android/firebase_firestore_settings_android_test.cc:1:10: fatal error: 'firestore/src/android/firebase_firestore_settings_android.h' file not found
  #include "firestore/src/android/firebase_firestore_settings_android.h"
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.
```

**Comment by dconeybe** [comment]
Ahh, `firebase_firestore_settings_android_test.cc` is obsolete. It was deleted in cl/329734038 in Sept 2020 but I guess that deletion didn't get propagated into this GitHub repository. I'll delete it from this PR.

**Review by jonsimantov — CHANGES_REQUESTED** [review]
Looks like two tests are still failing on Android:
[  FAILED  ] TypeTest.TestCanReadAndWriteNullFields
[  FAILED  ] TypeTest.TestCanReadAndWriteArrayFields

Could you (ideally) fix them or (alternately) skip them with the TODO?

**Comment by dconeybe** [comment]
@jonsimantov: Those two failing tests (TestCanReadAndWriteNullFields and TestCanReadAndWriteArrayFields) appear to be transient failures. Looking at the code, each test case was using a hardcoded document, leaving room for tests to interfere with each other or even other unrelated parallel test runs interfering with each other. I suspect that is what happened here. To fix, I've change the test code in `firestore/integration_test_internal/src/type_test.cc` to use a randomly-generated document name, to prevent interference.

**Review by jonsimantov — APPROVED** [review]

**Pull request merged**
